package com.team208.controllers;

import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.team208.domain.StudentEntity;
import com.team208.domain.StudentRepository;

@Controller
@RequestMapping(path="/team208") 
public class MainController {
	
	// This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
	@Autowired 
	private StudentRepository userRepository;
	
	 @RequestMapping("/")
	  @ResponseBody
	  public String index() {
	    return "Hello World!!!  Team208 Homepage";
	  }
	 
	 @GetMapping(path="/login")
	 public @ResponseBody StudentEntity login(@RequestParam Long userId, @RequestParam String password ) {
		 StudentEntity n = userRepository.findByNEUId(userId);
	
		 if(password.equals(n.getPassword())) {
			 return n;
		 }else
			 return null;
			
		}
	 //registerUser?studentDBid=1&userId='01226315'&name='rachana'&userRole='student'&password='zzeeddqq'&email='tondare@gmail.com'
	 @GetMapping(path="/registerUser") // Map ONLY GET Requests
		public @ResponseBody String addNewUser (@RequestParam Long userId, @RequestParam String name, @RequestParam String userRole,
				@RequestParam String password, @RequestParam String email) {
			// @ResponseBody means the returned String is the response, not a view name
			// @RequestParam means it is a parameter from the GET or POST request

		
			StudentEntity n = new StudentEntity();
			n.setStudentId(userId);
			n.setName(name);
			n.setUserRole(userRole);
			n.setPassword(password);
			n.setEmail(email);
			userRepository.save(n);
			return "Saved";
		}
	 
	 @GetMapping(path="/all")
		public @ResponseBody Iterable<StudentEntity> getAllUsers() {
			// This returns a JSON or XML with the users
			return userRepository.findAll();
		}
	 
	 
	 @GetMapping(path="/findStudent")
		public @ResponseBody StudentEntity findStudent(@RequestParam int userId ) {
		 List<Integer> ids = new ArrayList<>();
		 
		 try {
		 ids.add(userId);
		 }catch(Exception e){
			  e.printStackTrace();
		 }
		 Iterable<StudentEntity> studs = userRepository.findAllById(ids);
		 StudentEntity stud = null ;
			for(StudentEntity s : studs) {
				
				stud = s;
			}
			return stud;
			
		}
	
}
